- hosts: all
  tasks:
    - name: stop sshguard
      become: yes
      systemd:
        name: sshguard
        state: stopped
        enabled: false
    - name: install python3
      become: yes
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-pip
    - name: install locust
      become: yes
      pip:
        name: "{{ packages }}"
      vars:
        packages:
          - locustio
